baseurl = "rustyoz.github.io"
languageCode = "en-au"
title = "Russell Oliver"
Copyright = "All rights reserved - 2024"

[module]
[module.hugoVersion]
extended = false
min = "0.116.0"

[params]
  githubName = "rustyoz"
  twitterName = "rustyoliver"
   facebookName = "russelloliver"
 [[menu.main]]
  name = "Home"
  weight = -130
  identifier = "home"
  url = "/"
  
[[menu.main]]
  name = "Blog"
  weight = -120
  identifier = "blog"
  url = "/blog/"