baseurl = "rustyoz.github.io"
languageCode = "en-au"
title = "Russell Oliver"
Copyright = "All rights reserved - 2024"

[module]
[module.hugoVersion]
extended = false
min = "0.116.0"

[params]
  githubName = "rustyoz"
  twitterName = "rustyoliver"
  facebookName = "russelloliver"
  homeCollectionTitle = 'Posts'
  homeCollection = 'posts'
 
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/russelloliver2"

[[params.social]]
name = "twitter"
url = "https://x.com/rustyoliver"


[[params.social]]
name = "github"
url = "https://github.com/rustyoz"